### ISSUE TITLE
Unified Configuration: Sinatra & Node

### ISSUE THREAD

**Issue by bshouse** [bshouse/geotweeter#20]
Would it be possible to move the Sinatra configuration into the package.json so we do not have two configuration files?

I noticed that Ruby MongoClient documentation show a way to use the URI that is currently in the package.json: client = MongoClient.from_uri(uri)

Would it be difficult to have your Ruby app ready the package.json and have the DB URI and webserver IP/Port read from there?

Thank you.

**Comment by wderaad** [comment]
I'll look into it, I was thinking the same thing but it slipped my mind.
