### ISSUE TITLE
Create Heat Map based on Happiness of Region

### ISSUE THREAD

**Issue by wderaad** [bshouse/geotweeter#26]
Create Heat Map based on Happiness of Region
    -Text Analysis of Tweet Body
        -Smiley Faces

**Comment by bshouse** [comment]
Just as a note based on the latest data:
db.twitter.find({'properties.text': /😄|😃|😀|😊|☺|😉|😍|😘|😚|😗|😙|😜|😝|😛|😁|😇|😏|👮|👷|👶|👦|👧|👨|👩|👴|👵|👱|👼|👸|😺|😸|👹|👽|💩/}).count()
290101

**Comment by wderaad** [comment]
Sweet all add these to the to the textual smiley faces!

**Comment by bshouse** [comment]
The full text index can really help...

```
db.twitter.find({'properties.text': /😄|😃|😀|😊|☺|😉|😍|😘|😚|😗|😙|😜|😝|😛|😁|😇|😏|👮|👷|👶|👦|👧|👨|👩|👴|👵|👱|👼|👸|😺|😸|👹|👽|💩/}).count()
2015-04-25T14:00:55.947-0600 [conn14] command csci.$cmd command: count { count: "twitter", query: { properties.text: /😄|😃|😀|😊|☺|😉|😍|😘|😚|😗|😙|😜|😝|😛|😁|😇|😏|👮|👷|👶|👦|👧|👨|👩|👴|👵|👱|👼|👸|😺|😸|👹|👽|💩/ }, fields: {} } planSummary: COLLSCAN keyUpdates:0 numYields:0 locks(micros) r:185706850 reslen:48 185706ms

db.twitter.ensureIndex({'properties.text': 'text'},{'default_language': 'none'})

db.twitter.find({ $text: { $search: "😄 😃 😀 😊 ☺ 😉 😍 😘 😚 😗 😙 😜 😝 😛 😁 😇 😏 👮 👷 👶 👦 👧 👨 👩 👴 👵 👱 👼 👸 😺 😸 👹 👽 💩"} }).count()
2015-04-25T14:03:50.594-0600 [conn14] command csci.$cmd command: count { count: "twitter", query: { $text: { $search: "😄 😃 😀 😊 ☺ 😉 😍 😘 😚 😗 😙 😜 😝 😛 😁 😇 😏 👮 👷 👶 👦 👧 👨 👩 👴 👵 👱 👼 👸 😺 �..." } }, fields: {} } planSummary: TEXT { _fts: "text", _ftsx: 1 } keyUpdates:0 numYields:0 locks(micros) r:216269 reslen:48 216ms
```

RegEx: 185706ms vs Text: 216ms

There is one difference I cannot account for. The RegEx finds 290101 matches, the full text search only finds 101119 matches. I suspect it has something to do with tweets that have more than one smiley.

**Comment by bshouse** [comment]
I found even more smileys:
    db.twitter.find({ $text: { $search: "😄 😃 😀 😊 ☺ 😉 😍 😘 😚 😗 😙 😜 😝 😛 😁 😇 😏 👮 👷 👶 👦 👧 👨 👩 👴 👵 👱 👼 👸 😺 😸 👹 👽 💩 :) :p :P :-) :D :-D :-p _:-P ;) ;-) (^_^) ^_^ ^^ ^-^ (^-^) :-) :o) :] :3 :c) :> =] 8) 8-D 8D x-D xD X-D XD =-D =D =-3 =3 #-) %-) %) \o/ _\0/_ >^_^< <^!^> ^/^ （_^_^_） §^。^§ (^<^) (^.^) (^ム^) (^・^) (^。^) (^_^.) (^_^) (^^) (^J^) ＼(~o~)／ ＼(^o^)／ ＼(-o-)／ ヽ(^。^)ノ ヽ(^o^)丿 (_^0^_) (_^^)v (^^)v (^_^)v (＾▽＾)（・∀・）（　´∀｀）（⌒▽⌒）（＾ｖ＾）（’-’_)（●＾o＾●）（＾ｖ＾）（＾ｕ＾）（＾◇＾）( ^)o(^ ) (^O^) (^o^) (^○^) )^o^( (_^▽^_) (✿◠‿◠) 😀 😁 😂 😃 😄 😅 😆 😇 😈 😉 😊 😋 😌 😍 😎 😏"} }).count()

Count from current data set's full text index: 566272

Update: This set is likely bogus because I forgot to quote the smileys with spaces in them...

**Comment by wderaad** [comment]
Text searching is still returning 0 for my database where regex is returning plenty of documents. I'm going to check my Mongo and make sure I'm using the same version. 

Update: So I'm using a newer version so I'll downgrade and see if the full text search will work.

**Comment by bshouse** [comment]
I don't think it has anything to do with your version of Mongo. I just think that the Full Text Index does not index the classic compound text smileys :) , but the character based ones are :relieved: . You will probably have to use RegEx for the classic compound text smileys. The full text index will not help there... :disappointed:

**Comment by bshouse** [comment]
Even more strangeness....

```
> db.twitter.find({"properties.text":{$regex:/\:P/}}).count()
2971
> db.twitter.find({"properties.text":{$regex:/\:\-P/}}).count()
385
> db.twitter.find({$text: { $search: ":-P", $language: 'none'}}).count()
26117
> db.twitter.find({$text: { $search: ":P", $language: 'none'}}).count()
26117
```

**Comment by wderaad** [comment]
Your definitely right. I am also getting the same thing:

```
> db.twitter.find({$text: { $search: ":P", $language: 'none'}}).count()
3905
> db.twitter.find({$text: { $search: ":-P", $language: 'none'}}).count()
3905
> db.twitter.find({$text: { $search: ":-p", $language: 'none'}}).count()
3905
> db.twitter.find({$text: { $search: ":p", $language: 'none'}}).count()
3905
> db.twitter.find({$text: { $search: ":P :-P :p :-p", $language: 'none'}}).count()
3905
```

```
> db.twitter.count({"properties.text":{$regex:/\:P/}})
495
> db.twitter.count({"properties.text":{$regex:/\:\-P/}})
50
> db.twitter.count({"properties.text":{$regex:/\:\-p/}})
14
> db.twitter.count({"properties.text":{$regex:/\:p/}})
672
> db.twitter.count({$or:[{"properties.text":{$regex:/\:p/}},{"properties.text":{$regex:/\:P/}},{"properties.text":{$regex:/\:\-P/}},{"properties.text":{$regex:/\:\-p/}}]})
1226
```

The full text search definitely is not treating any of those smiley faces differently, the same thing is happening with the smiley faces containing D's. 

How do you feel about using full-text search for the emojis and the regex for all other smiley faces?

**Comment by bshouse** [comment]
I don't think Mongo is giving us much choice. I would even support full-RegEx at this point. The full text index seems to be screwy. RegEx may be slow, but it works.

Please let me know if I can do anything to assist.
