### ISSUE TITLE
Indexing (createIndexes.js)

### ISSUE THREAD

**Issue by wderaad** [bshouse/geotweeter#27]
Hey @bshouse when I am indexing text do I want to have a compound index with country? I noticed most of the indexes you create do, such as:
    '{"properties.country": 1, "properties.local_doy": 1}',

I'm currently just text indexing the "text" of the tweet as follows:
    '{"properties.text": "text"}'

**Comment by wderaad** [comment]
If I do need to use a compound index (it looks like I will), I believe Mongo only allows for one full text index . . . but we would want at least two one at the country level and one at the state level correct?

Maybe more if we want to identify if properties.point is true/false?

**Comment by bshouse** [comment]
So, I would just make one big compound index...

{ "properties.country": 1, "properties.state": 1, "properties.text": "text" }

I am not Mongo expert, but that would be my first attempt.  If that does not work, I would do just a simple text index and then leverage the other existing indexes to track down information. For example:
1. search the text index for "word" and return _ID
2. search country/state index for _ID

@priyanka57 may have more insight about Mongo indexes. I will also try to do some reading, but I remember from the lecture that column order and ascending/descending have serious performance impacts if not used properly.  I know the .explain() function can give you some information about how it is all working in the running setup.

**Comment by bshouse** [comment]
[If the compound text index includes keys preceding the text index key, to perform a $text search, the query predicate must include equality match conditions on the preceding keys.](http://docs.mongodb.org/manual/core/index-text/#text-index-compound)

This makes the two step option sound better. Otherwise you would have to search the text and specify values for the other keys (state/country). So, it would require that you query the text of each state/country combination separately.

**Comment by wderaad** [comment]
Hey so I've run into a questions you guys might be able to answer. @bshouse @priyanka57 

Regarding the Node Mongo Driver vs Interacting with the Mongo Shell directly. I am getting two different indexes using the ensureIndex commands 

Indexing with the Node Mongo Driver, does not properly index for full text search where as indexing with the mongo shell does. 

Mongo: Full Text Index using db.twitter.ensureIndex({"properties.text":"text})
    {
        "v" : 1,
        "key" : {
            "_fts" : "text",
            "_ftsx" : 1
        },
        "name" : "properties.text_text",
        "ns" : "csci.twitter",
        "weights" : {
            "properties.text" : 1
        },
        "default_language" : "english",
        "language_override" : "language",
        "textIndexVersion" : 2
    }

Node: Full Text Index using collection.ensureIndex() for  {"properties.text":"text}
    {
        "v" : 1,
        "key" : {
            "{"properties.text": "text"}" : 1
        },
        "name" : "{\"properties.text\": \"text\"}_1",
        "ns" : "csci.twitter"
    }

Looking at the other indexes I'm not sure if any of the compound indexes from the Node createIndexes are working correctly either as they have a similarly weird format . . . Any insights from someone more familiar with mongo would be helpful. 

**_If you don't know the answer to this at first glance, please don't waste any time. I don't think full text search is going to work regardless since I think it only seems to recognize words and not non-alphabetical characters such as smiley faces.**_

**Comment by bshouse** [comment]
I will look into this a little, but I suspect that if you set the language to "none" it would index simileys too.

[If you specify a language value of "none", then the text index uses simple tokenization with no list of stop words and no stemming.](http://docs.mongodb.org/manual/core/index-text/)

**Comment by bshouse** [comment]
I just ran a local test and it appears the indexes are being used.

> db.twitter.find({'properties.country': 'North Korea'}).count()
> 116
> db.twitter.find({'properties.country': 'North Korea'}).explain()
>     {
>         "cursor" : "BtreeCursor properties.country_1",
>         "isMultiKey" : false,
>         "n" : 116,
>         "nscannedObjects" : 116,
>         "nscanned" : 116,
>         "nscannedObjectsAllPlans" : 116,
>         "nscannedAllPlans" : 116,
>         "scanAndOrder" : false,
>         "indexOnly" : false,
>         "nYields" : 0,
>         "nChunkSkips" : 0,
>         "millis" : 0,
>         "indexBounds" : {
>             "properties.country" : [
>                 [
>                     "North Korea",
>                     "North Korea"
>                 ]
>             ]
>         },
>         "server" : "book4:27017",
>         "filterSet" : false
>     }

The **"cursor" : "BtreeCursor** indicates that it is using the index.

**Comment by bshouse** [comment]
Further research shows that Mongo is not using the compound indexes. I can hint to force it, but it is faster to use the non-compound index. It seems like mongo knows this and uses what's best:

http://stackoverflow.com/questions/22499148/mongodb-using-wrong-index

**Comment by wderaad** [comment]
I just thought that our compound indexes looked strange compared to the regular indexes, and thought it may be due to the driver. It doesn't seem to matter with our data set, since were getting fast enough performance with the individual indexes, event counting using full text search. 

Even when specifying language as none it does not seem to recognize non-alphabetical characters, either that or my data set doesn't contain a single smiley face (for reference it contains the word "hi" in 1,982 documents). 

I'm going to keep looking into it but also try using $regex.

**Comment by wderaad** [comment]
I'm pretty sure the node driver ensureIndex is only expecting a string, for the single index with default sort order. I got the full text to work by adding another function specifically to handle it, I pushed it to my branch if your interested, but I think we would have to do something similar to get the compound indexes to work. I'll look into it after I finish this.

**Comment by bshouse** [comment]
I am not sure I see the difference in the method you added. It looks like it is just a function dedicated to the text index.  Could you please explain how it is different?

Thank you.

**Comment by wderaad** [comment]
If I add the string: `'{"properties.text" : "text"}'` to the index array, it is interpreted as:
`ensureIndex('{"properties.text" : "text"}',function(error){});`
When it needs to be interpreted as:
`ensureIndex({"properties.text" : "text"},function(error){});`
**_i.e. not a string.**_ 
Same thing is happening with our compound indexes, they are being interpreted as:
`ensureIndex('{"properties.country": 1, "properties.point": 1}',function(error){});`
Instead of:
`ensureIndex({"properties.country": 1, "properties.point": 1},function(error){});`

Anyhow it doesn't matter for me, I'm using $regex which indexing does not improve performance. But we can remove all of the compound indexes if you would like.

**Comment by bshouse** [comment]
Thank you for the clarification. You could not be more right.  I will submit a pull request shortly to address them problem.
