### ISSUE TITLE
Counting the media tweets at the world level 

### ISSUE THREAD

**Issue by priyanka57** [bshouse/geotweeter#34]
Creating a script to see how many images are tweeted at the world perspective.

**Comment by priyanka57** [comment]
I have modified two functions and added two sub-functions to show the image count in the createWorldSummary.js file. Still working on it.

**Comment by bshouse** [comment]
@Priyanka57 This can be closed now. Nice work. :smile:

**Comment by priyanka57** [comment]
Thank you!!
